changes made meshery link
meshery/meshery-operator pull request #184
Opened 2021-07-01 21:22 UTC by chetak123

Signed-off-by: Ayushman Mishra <ayushvidushi01@gmail.com>

**Description**

Changing the layer5 link to meshery link

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-07-01 21:28 UTC, sayantan1413 requested changes

2021-07-01 21:28 UTC, sayantan1413 commented on .github/PULL_REQUEST_TEMPLATE.md
> +**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
Let not change this line . If there is any endpoint with **layer5io** then only change it to **meshery** rest keep as it is.

2021-07-01 21:37 UTC, sayantan1413 approved these changes
LGTM

2021-07-02 04:48 UTC, leecalcote approved these changes
Thanks, gents.

2021-07-02 04:48 UTC, merged