M uzair s15/operator/logs
meshery/meshery-operator pull request #560
Opened 2024-07-18 19:16 UTC by MUzairS15

**Description**

This PR fixes #
1. Initialise logging for meshery-operator.
2. Ensures the operator redeploys the controllers, if they are deleted or their status isn't Running (k8s world status)
3. Adds health check for MeshSync

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-18 19:17 UTC, MUzairS15 commented
TODO: Replace logging with meshkit logger, redefine errors to be meshkit-errors.

2024-07-18 19:23 UTC, MUzairS15 commented
https://github.com/user-attachments/assets/575ebdd0-8593-4ea1-9165-4588d3bc51e7

2024-07-18 19:48 UTC, leecalcote commented on controllers/broker_controller.go
> +		r.Log.Error(err, "broker reconcilation failed")
Reconciliation failures means what?

2024-07-18 19:49 UTC, leecalcote commented on controllers/broker_controller.go
> +		r.Log.Error(err, "unable to get the broker endpoint")
meaning that the endpoint is undefined or that a network-based attempt failed?

2024-07-18 19:50 UTC, leecalcote commented on controllers/broker_controller.go
> +		r.Log.Error(err, "unable to update broker resource")
Meaning that the resource couldn't be found or that it is present but the operator doesn't have permission or something else?

2024-07-18 19:50 UTC, leecalcote commented on controllers/broker_controller.go
> +		r.Log.Error(err, "unable to update broker resource")
Meaning that the configuration was rejected from Kube API or that the resource isn't present or that the requested configuration was missing or invalid or what?

2024-07-18 19:51 UTC, leecalcote commented on controllers/error.go
> +	return errors.New(ErrGetMeshsyncCode + ":" + "Unable to get meshsync resource" + err.Error())
Meaning that the custom resource was never created?

2024-07-18 19:52 UTC, leecalcote requested changes
As a user troubleshooting Meshery deployment, I'm not confident that I would know what to do when seeing these errors.

2024-07-18 19:53 UTC, leecalcote commented
@innocentrda, your feedback here is helpful.

2024-07-18 19:54 UTC, leecalcote commented
Is there an adjoining addition to the https://docs.meshery.io/guides/troubleshooting/meshery-operator-meshsync guide?

2024-07-19 06:41 UTC, innocentrda commented
> As a user troubleshooting Meshery deployment, I'm not confident that I would know what to do when seeing these errors.

That's true. It's a good improvement to see those errors but being a bit detailed on why those errors and what to do can be helpful.

2024-07-22 06:58 UTC, merged